name: Docker Hub Build & EC2 Deploy

on:
  push:
    branches: [main]

jobs:
  dockerhub-build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejsapp .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejsapp

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejsapp
          sudo docker stop nodejsapp || true
          sudo docker rm nodejsapp || true
          sudo docker run -d --name nodejsapp -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nodejsapp

