name: AWS ECR Private Build & Push

on:
  push:
    branches: [main]

jobs:
  ecr-private-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push to Private ECR
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        REGION=us-east-1
        REPO_NAME=nodejsapp
        IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME

        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
